/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import Utilerias.ConexionSQLServer;
import app.Daos.DaoLibro;
import app.model.BeanLibro;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import app.model.BeanAutor;
import app.Daos.DaoAutor;
import javax.swing.JOptionPane;

/**
 *
 * @author Eliel David
 */
public class ReadLibro extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private Connection con;
    private DaoLibro daoLibro;
    
    private DaoAutor daoAutor;
    private BeanAutor beanA = new BeanAutor();

    /**
     * Creates new form ReadUsuarios
     */
    public ReadLibro() {
        initComponents();
        try {
            con = ConexionSQLServer.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ReadLibro.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setLocationRelativeTo(null);
        actualizarTabla();
    }

    private void actualizarTabla() {
        daoLibro = new DaoLibro(con);
        daoAutor = new DaoAutor(con);

        List<BeanLibro> lista = daoLibro.getAll();

        for (BeanLibro bean : lista) {
            String autores = "";
            for (BeanAutor aut : bean.getAutores()) {
                autores += aut.getNombre() + " " + aut.getPrimer_apellido()+", ";
            }
            
            modelo = new DefaultTableModel(new String[]{"id_libro", "titulo", "ISBN", "Paginas", "Area", "Editorial", "Autores"}, 0);

            Object[] arreglo
                    = {bean.getId_libro(), bean.getTitulo(), bean.getISBN(), bean.getPaginas(),
                        bean.getArea().getNombre(), bean.getEditorial().getNombre(), autores};
            modelo.addRow(arreglo);

        }
        tblLibros.setModel(modelo);
    }

    public void busqueda(String bus) {
        if (bus.length() < 0) {
            actualizarTabla();
        } else {

            modelo = new DefaultTableModel(new String[]{"id_libro", "titulo", "ISBN","Paginas", "Area", "Editorial", "Autores"}, 0);
            List<BeanLibro> lista = daoLibro.getAll();
            for (BeanLibro bean : lista) {
                 String autores = "";
                 for (BeanAutor aut : bean.getAutores()) {
                autores += aut.getNombre() + " " + aut.getPrimer_apellido()+", ";
            }
                if (bean.getTitulo().toLowerCase().contains(bus.toLowerCase())) {
                    Object[] arreglo = {bean.getId_libro(), bean.getTitulo(), bean.getISBN(), bean.getPaginas(), bean.getArea(),
                        bean.getEditorial(),autores};
                    modelo.addRow(arreglo);
                }

            }
        }
        tblLibros.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        tblLibros.setModel(  modelo = new DefaultTableModel(new String[]{"id_libro", "Titulo","Autor", "ISBN",
            "Paginas", "id_area", "id_editorial"}, 0));
tblLibros.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblLibrosMouseClicked(evt);
    }
    });
    tblLibros.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            tblLibrosKeyPressed(evt);
        }
    });
    jScrollPane1.setViewportView(tblLibros);

    jPanel1.add(jScrollPane1);
    jScrollPane1.setBounds(0, 30, 730, 231);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("LISTA LIBROS");
    jPanel1.add(jLabel1);
    jLabel1.setBounds(170, 0, 170, 22);

    txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txtBusquedaKeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtBusquedaKeyReleased(evt);
        }
    });
    jPanel1.add(txtBusqueda);
    txtBusqueda.setBounds(130, 270, 230, 20);

    jButton1.setText("Regresar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton1);
    jButton1.setBounds(427, 270, 90, 23);

    jLabel3.setText("Buscar");
    jPanel1.add(jLabel3);
    jLabel3.setBounds(20, 270, 70, 14);

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoreadusuario.png"))); // NOI18N
    jPanel1.add(jLabel2);
    jLabel2.setBounds(0, 0, 690, 300);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        // TODO add your handling code here:
        busqueda(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            busqueda(txtBusqueda.getText());
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void tblLibrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLibrosKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblLibrosKeyPressed

    private void tblLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibrosMouseClicked
        int id = (int) modelo.getValueAt(tblLibros.getSelectedRow(), 0);
BeanLibro bean= new BeanLibro();
        bean = daoLibro.get(id);

        new UpdateLibro(bean).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_tblLibrosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
